application: design-hub-web-716
version: 1
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- channel_presence

handlers:
- url: /assets/js
  static_dir: assets/js

- url: /assets/css
  static_dir: assets/css

- url: /assets/img
  static_dir: assets/img

#Ritesh's site
- url: /finalMyringotomy.html
  static_files: finalMyringotomy.html
  upload: finalMyringotomy.html

- url: /sendmessage
  script: chat.app

- url: /slackchat
  script: chat.app

- url: /_ah/channel/connected/
  script: chat.app

- url: /_ah/channel/disconnected/
  script: chat.app

- url: /chat
  script: chat.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
